version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: image_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "America/Manaus"
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
    restart: always

